name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print current directory after checkout
        run: |
          echo "Current directory after checkout:"
          pwd
          ls -al
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: './my-app'
      - name: Print Node.js version
        run: node -v
      - name: Print npm version
        run: npm -v
      - name: Print environment variables
        run: |
          echo "Environment variables:"
          env
      - name: Install dependencies
        run: |
          pwd
          ls -al                    
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed."
      - name: Build Next.js app
        run: |
          pwd
          ls -al          
          echo "Building Next.js app..."
          npm run build
          echo "Next.js app built."
      - name: Export Next.js app
        run: |
          pwd
          ls -al          
          echo "Exporting Next.js app..."
          npm run export
          echo "Next.js app exported."
      - name: List files in out directory
        run: |
          echo "Files in out directory:"
          ls -al out
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
          name: nextjs-site
          retention-days: 1