name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Navigate to project directory
        run: cd my-app

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Export Next.js app
        run: npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
          name: nextjs-site
          retention-days: 1